### ISSUE TITLE
Review version4/00 Intro/00 zero-config

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/webpack-3.x-by-sample#121]
Steps go through the sample and check that you can reproduce it and  correct any typo or entry.

**Comment by PedroJesusRomeroOrtega** [comment]
Ok, I'm going with it!

**Comment by PedroJesusRomeroOrtega** [comment]
* I ran it and ok, the dist folder was created.
* I am going to put a pull request with the correction of some typos.
* Only one thing, at the end I try to do a `npm start` with no success; is the espected behaviour?

Regards.

**Comment by brauliodiez** [comment]
Yes there's no "start" command only build.

Please raise the pull request, I'm keen on reviewing it, thanks for the good work :)
