### ISSUE TITLE
Migrate 01 custom css to use the new mini extract plugin

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/webpack-3.x-by-sample#157]
Sample:

https://github.com/Lemoncode/webpack-by-sample/tree/master/version%204/01%20Styles/01%20custom-css

In the master class we cover this.

https://www.valentinog.com/blog/webpack-4-tutorial/#webpack_4_extracting_CSS_to_a_file

it would be great to update both code and readme.

**Comment by maximo-calero** [comment]
I created a new pull request (#163 ) with the changes I made related wit this issue.

I made these changes as an alternative to extract-text-webpack-plugin because I understood that the mini-css-extract-plugin is only compatible with 4.2+ version of webpack.
