### ISSUE TITLE
Add sample misc, alias (webpack, ts, jest)

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/webpack-3.x-by-sample#200]
Start from 

https://github.com/Lemoncode/jest-testing-by-sample/tree/master/frontend/02%20Plain%20Vanilla

O:-)

**Comment by brauliodiez** [comment]
Nice implementation !! :)

**Comment by LissetteIbnz** [comment]
@brauliodiez,  I think this issue can be closed
