### ISSUE TITLE
Fix babel core-js warning

### ISSUE THREAD

**Issue by nasdan** [Lemoncode/webpack-3.x-by-sample#213]

**Comment by LissetteIbnz** [comment]
@Nasdan, you should explain this warning. I would like a post about that 👏😊

**Comment by nasdan** [comment]
@LissetteIbnz, it's this babel warning:

```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```
It means that right now babel is assuming that we are using `core-js@2` but it will be change in future, so it's required to feed corejs version in `.babelrc` file and we need to install same version in package.json to ensure that babel is using the right one. I don't know if it could be a post :)

**Comment by LissetteIbnz** [comment]
Yes, I know that. I mean what version. You have set core-js3. Saskia estaría tirándose de los pelos...
