### ISSUE TITLE
01 Styles/04 Handling Images

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/webpack-3.x-by-sample#53]
Review readme.md, fix typos / issues go throught step by step guide

**Comment by brauliodiez** [comment]
Assigned to mlopezperez

**Comment by mlopezperez** [comment]
@brauliodiez, this is supposed to be assigned to me, but I don't appear as "asignee". I didn't received any e-mail neither, just found it out by chance!

**Comment by nasdan** [comment]
@mlopezperez that was because we invite you to this repository and we cannot assign you before you accept it.
