### ISSUE TITLE
Replace tabs by spaces

### ISSUE THREAD

**Issue by nasdan** [Lemoncode/webpack-3.x-by-sample#62]
For examples in this [PR](https://github.com/Lemoncode/webpack-2.x-by-sample/pull/61/files#diff-65660d753012e947eb0e8676d6413c71R88), we can see how `hash:true` property has bad indentation:

```diff
+    new HtmlWebpackPlugin({
+      filename: 'index.html', //Name of file in ./dist/
+      template: 'index.html', //Name of template in ./src
+			hash: true,
+    }),
+    new webpack.ProvidePlugin({
```
That's because it using 3 `tabs` instead of 6 `spaces`
To resolve this, we have to replace by spaces in all necessary samples.

**Comment by jecaestevez** [comment]
This "bug"  remind me to the Silicon Valley episode https://m.youtube.com/watch?v=SsoOG6ZeyUI
